### ISSUE TITLE
Dodać Huberta Waśniewskiego do zespołu "simulator"

### ISSUE THREAD

**Issue by ondreo** [pb-iot/simulator#20]
Prosiłbym o dodanie Huberta Waśniewskiego (https://github.com/Jaaaaaxi) do zespołu "simulator", żebyśmy mogli współpracować bez wysyłania sobie kodu gołębiem pocztowym.

Nie jestem w stanie tego sam zrobić (takie ustawienia dostępu), a współpraca z Hubertem jest dla nas krytycznie ważna.

**Comment by sobek123** [comment]
To trzeba napsiac do tego kogos kto ten projekt caly stawial, bo on ma uprawnienia do tego

**Comment by ondreo** [comment]
@wvffle

**Comment by wvffle** [comment]
Fajnie, ze dopiero po takim czasie gosc dolacza do projektu. Dodany.
